# versione di docker compose
version: "3.8"

# inizia la definizione dei docker da avviare/creare
services:
# crea il docker tramite l'immagine e ne definisce le porte della api
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama

# crea il docker tramite l'immagine creata in locale
  ollama-api:         # work directory
    build: .          # crea l'immagione dal dockerfile nella cartella corrente
    # stdin_open: true  # mantiene STDIN standard per interazione terminale
    # tty: true         # crea uno speudo terminale
    # command: bash     # all'avvio del docker apre la bash
    depends_on:       # il docker dipende da ollama
      - ollama
    #volumes:
      #- ollama_api_data:/app/log
    container_name: ollama_api

  # webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama-prova:11434
  #   depends_on:
  #     - ollama
  #   volumes:
  #     - webui_data:/app/backend/data

volumes:
  ollama_data:
  webui_data: